platform :ios, '8.0'

target 'ZQBsaeDemo’ do
 pod 'YYKit','~> 1.0.9’
 pod 'Masonry','~> 1.1.0’
 pod 'JPush','~> 3.0.7’
 pod 'AFNetworking','~> 3.1.0’
 pod 'RongCloudIM/IMLib','~> 2.8.23’
 pod 'RongCloudIM/IMKit','~> 2.8.23’
 pod 'ZQProgressView','~> 0.0.1’
 pod 'WebViewJavascriptBridge', '~> 6.0.3'
end



